spring.application.name=gateway-service
server.port=${SERVER_PORT:8080}

spring.config.import=optional:nacos:${spring.application.name}.properties?group=DEFAULT_GROUP&refreshEnabled=true,optional:nacos:flashsale-common.properties?group=DEFAULT_GROUP&refreshEnabled=true
spring.cloud.nacos.server-addr=${NACOS_SERVER_ADDR:localhost:8848}
spring.cloud.nacos.discovery.namespace=${NACOS_NAMESPACE:public}
spring.cloud.nacos.discovery.group=${NACOS_GROUP:DEFAULT_GROUP}
spring.cloud.compatibility-verifier.enabled=false

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id=order-service-route
spring.cloud.gateway.routes[0].uri=lb://order-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/orders/**

spring.cloud.gateway.routes[1].id=core-service-route
spring.cloud.gateway.routes[1].uri=lb://core-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/**

management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.health.show-details=always
