# Core service centralized configuration
flashsale.dynamic.message=hello-from-nacos
flashsale.cache.product-detail.ttl-seconds=600
flashsale.cache.product-detail.null-ttl-seconds=60
flashsale.cache.product-detail.jitter-max-seconds=300
flashsale.cache.product-detail.rebuild-lock-seconds=10
flashsale.cache.product-detail.rebuild-thread-pool-size=4
flashsale.cache.product-list.ttl-seconds=300
flashsale.cache.product-list.jitter-max-seconds=180
flashsale.cache.product-list.rebuild-lock-seconds=8
flashsale.cache.warmup.product-detail-count=20
flashsale.ratelimit.product-list.rps=200
flashsale.ratelimit.product-detail.rps=500
